#4 Adapt getOrder method
ripe-tech/epir-processor-api-js pull request #1
Opened 2020-10-01 16:00 UTC by 3rdvision

| - | - |
| --- | --- |
| Issue | https://github.com/ripe-tech/epir-core/issues/4 |
| Dependencies | https://github.com/hivesolutions/yonius/pull/18 |
| Decisions | • Adapt `method` method instead of mock method. <br> • Adapt example to call `method`. <br> • Add pull request and bug report template.  |

2020-10-01 16:02 UTC, gcandal commented on js/order.js
> +        async getOrder(number, options = {}) {
This should be a dumb API client, meaning that you just `this.get(url, options)` without changing them. Clients of the API will have to build the options to contain a `X-Secret-Key` header by themselves.

2020-10-01 16:02 UTC, gcandal commented on .github/PULL_REQUEST_TEMPLATE.md
> +| - | - |
Sorry to be a PITA, but this must go in a different PR.

2020-10-02 13:11 UTC, gcandal requested changes

2020-10-02 13:11 UTC, gcandal commented on js/base.js
> +            options.headers["x-secret-key"] = this.token;
Fix the casing

2020-10-02 15:39 UTC, gcandal approved these changes

2020-10-28 10:06 UTC, joamag requested changes

2020-10-28 10:06 UTC, joamag commented on examples/simple.js
> +const orderNumber = 5555;
this is not ok

2020-10-28 10:06 UTC, joamag commented on examples/simple.js
> +const orderNumber = 5555;
let's use an env variable

2020-10-28 15:41 UTC, joamag approved these changes

2020-10-28 15:41 UTC, merged